# Generated by Django 4.2.1 on 2023-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=160, null=True)),
                ('endereco', models.CharField(max_length=260, null=True)),
                ('forma_de_pagamento', models.CharField(choices=[('PX', 'Pix'), ('DIN', 'Dinheiro'), ('CC', 'Credito ou Débito')], default='DIN', max_length=3)),
                ('pedido', models.CharField(blank=True, max_length=260, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pedido', models.CharField(choices=[('SNF', 'SENDO FEITO'), ('ACO', 'A CAMINHO'), ('ETE', 'ENTREGUE')], default='SNF', max_length=3)),
                ('hora_pedido', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
