# Generated by Django 4.2.1 on 2023-05-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='num_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.pedido'),
        ),
    ]
