# Generated by Django 4.2.1 on 2023-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_clients_num_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='num_pedido_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
