# Generated by Django 4.2.1 on 2023-05-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_pedido_num_pedido_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='num_pedido_id',
        ),
    ]
