# Generated by Django 4.2.1 on 2023-05-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_remove_pedido_num_pedido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='num_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp.pedido'),
        ),
    ]
