# Generated by Django 4.2.1 on 2023-05-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_alter_clients_num_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='status_mensage',
            field=models.CharField(choices=[('snt', 'Enviada'), ('dvr', 'Entregue'), ('rad', 'LIDA')], default='snt', max_length=3),
        ),
    ]
