# Generated by Django 4.2.1 on 2023-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_clients_conversation_id_clients_status_mensage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status_mensage',
            field=models.CharField(choices=[('snt', 'Enviada'), ('dvr', 'Entregue'), ('rad', 'Lida')], default='snt', max_length=3),
        ),
    ]
